### ISSUE TITLE
config.yaml not created

### ISSUE THREAD

**Issue by Qubits01** [yellowcrescent/psvpack#1]
Hi,
I installed the program successfully (as non-root).
However the config is not created.
I enter "psvpack" and the help is displayed.
the folder in /.config/ is not created, nur the config file.
putting psvpack s neptunia prints

`ERROR: Failed to write configuration: [Errno 2] No such file or directory: '/home/myname/.config/psvpack/config.yaml'
ERROR: Failed to load config from /home/myname/.config/psvpack: [Errno 2] No such file or directory: '/home/myname/.config/psvpack'
WARNING: Using default configuration
INFO: Updating cached TSV file from
ERROR: Failed to fetch TSV file: Invalid URL '': No schema supplied. Perhaps you meant http://?
ERROR: Failed to parse TSV file: [Errno 2] No such file or directory: '/home/ultrasee/.config/psvpack/tsv/'
!! No results.
`

Edit: I fixed it for me by modifying line 30+31 of util.py:

    #if fpath is None:
    fpath = get_platform_confpath('config.yaml')

seems like only calling the program with "psvpack" make fpath!=none

**Comment by yellowcrescent** [comment]
@Qubits01 Thanks for the report. Looks like the default config creation function was expecting a filename to be passed, but the CLI parser was passing a directory instead. Oops. Fixed in 4069e1f.

Although the Qt5 GUI is still very much a learning experience/work-in-progress, you can also give it a try by running `psvpack-qt`. Just be sure to install PyQt5 (`python3-pyqt5` package on most distros) first. The functionality is limited, as it can only browse and search, but might be more convenient than using `psvpack s` for finding the product ID.
